[project]
name = "agentx-source"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.8",
    "torch>=2.9.1",
    "transformers>=4.57.1",
]
