[project]
name = "agentx-source"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.8",
    "python-iso639>=2025.11.16",
    "termcolor>=3.2.0",
    "torch>=2.9.1",
    "transformers>=4.57.1",
    "sentencepiece>=0.2.1",
    "faiss-cpu>=1.13.0",
]
